# Generated by Django 3.1.7 on 2021-04-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_auto_20210421_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupons',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
