# Generated by Django 3.1.7 on 2021-04-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0005_auto_20210421_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='end',
            new_name='valid_from',
        ),
        migrations.RenameField(
            model_name='coupons',
            old_name='start',
            new_name='valid_to',
        ),
    ]
