# Generated by Django 3.1.7 on 2021-04-22 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0006_auto_20210421_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valid_from_date', models.DateField()),
                ('valid_to_date', models.DateField()),
                ('start', models.BooleanField(default=False)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin1.categories')),
            ],
        ),
    ]
