# Generated by Django 3.1.7 on 2021-04-24 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0008_auto_20210422_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='valid_from_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='valid_to_date',
            new_name='to_date',
        ),
    ]
