# Generated by Django 3.1.7 on 2021-04-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0009_auto_20210424_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='from_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='to_date',
            new_name='start_date',
        ),
    ]
