# Generated by Django 3.1.7 on 2021-04-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0010_auto_20210424_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_name',
            new_name='name',
        ),
    ]
